//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivo_documento_digital
    {
        public int id_archivo_documento_digital { get; set; }
        public string nombre { get; set; }
        public string ruta { get; set; }
        public string extension { get; set; }
        public Nullable<int> id_solicitud_factura { get; set; }
        public string ruta_origen { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario { get; set; }
    
        public virtual solicitud_factura solicitud_factura { get; set; }
    }
}
