//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion_de_gastos
    {
        public int id_asignacion { get; set; }
        public Nullable<int> proyecto { get; set; }
        public Nullable<int> gasto { get; set; }
        public string mes { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<decimal> acumulado { get; set; }
        public Nullable<int> estatus { get; set; }
        public string poliza { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> userupd { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_gasto { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> numero_gasto { get; set; }
        public Nullable<int> id_comprobacion_detalle { get; set; }
    
        public virtual gasto gasto1 { get; set; }
        public virtual proyecto proyecto1 { get; set; }
    }
}
