//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobranza_traspaso
    {
        public int id_cobranza_traspaso { get; set; }
        public Nullable<int> id_proyecto_factura { get; set; }
        public Nullable<decimal> abono { get; set; }
        public Nullable<int> userupd { get; set; }
        public Nullable<System.DateTime> stamp { get; set; }
    
        public virtual proyecto_factura proyecto_factura { get; set; }
    }
}
