//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobranza
    {
        public int id_folio { get; set; }
        public Nullable<int> cobranza1 { get; set; }
        public Nullable<int> pago { get; set; }
        public string referencia { get; set; }
        public Nullable<decimal> abono { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<int> factura { get; set; }
        public string serie { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> folio_contpaq { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> userupd { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string maquina { get; set; }
        public string tipo_registro { get; set; }
    
        public virtual factura factura1 { get; set; }
    }
}
