//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacto
    {
        public int id_contacto { get; set; }
        public Nullable<int> cliente { get; set; }
        public string nom_contacto { get; set; }
        public string email { get; set; }
        public string puesto { get; set; }
        public string observaciones { get; set; }
    
        public virtual cliente cliente1 { get; set; }
    }
}
