//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrasena
    {
        public int id_contrasenas { get; set; }
        public string proyectos { get; set; }
        public string tiempos { get; set; }
        public string cancelacion { get; set; }
        public string correo { get; set; }
        public string contrasena_correo { get; set; }
        public Nullable<int> estatus_tiempo { get; set; }
        public string correo_alter { get; set; }
        public string contrasena_correo_alter { get; set; }
        public string clasificacion { get; set; }
    }
}
