//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class correo_time
    {
        public int id_correo { get; set; }
        public Nullable<int> empleado { get; set; }
        public Nullable<int> quincena { get; set; }
        public string mes { get; set; }
        public Nullable<int> anio { get; set; }
        public string de { get; set; }
        public string para { get; set; }
        public string copia { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<System.DateTime> stamp { get; set; }
    }
}
