//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.empleado_actividad = new HashSet<empleado_actividad>();
        }
    
        public int id_empleado { get; set; }
        public string num_empleado { get; set; }
        public string nom_empleado { get; set; }
        public string apellido { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<int> num_departamento { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> estatus_tiempo { get; set; }
        public string rfc { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> userupd { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string maquina { get; set; }
        public string alias { get; set; }
        public Nullable<int> actualizacontrasenia { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_dia { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual nivel nivel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado_actividad> empleado_actividad { get; set; }
    }
}
