//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class envio_correo
    {
        public int id_envio { get; set; }
        public Nullable<int> id_solicitud { get; set; }
        public string de { get; set; }
        public string para { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual solicitud_factura solicitud_factura { get; set; }
    }
}
