//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.cobranzas = new HashSet<cobranza>();
            this.factura_detalles = new HashSet<factura_detalles>();
        }
    
        public int id_factura { get; set; }
        public string serie { get; set; }
        public Nullable<int> proyecto { get; set; }
        public Nullable<int> credito { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha_cancelacion { get; set; }
        public string motivo { get; set; }
        public string moneda { get; set; }
        public Nullable<decimal> tipo_cambio { get; set; }
        public string total_dolar { get; set; }
        public Nullable<System.DateTime> fecha_credito { get; set; }
        public Nullable<decimal> debe { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> userupd { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string mes { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<System.DateTime> stamp { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string maquina { get; set; }
        public string tipo_registro { get; set; }
        public string tipo_cancelacion { get; set; }
        public Nullable<int> traspaso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cobranza> cobranzas { get; set; }
        public virtual proyecto proyecto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_detalles> factura_detalles { get; set; }
    }
}
