//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hora_no_asignable
    {
        public int id_hora_no_asignable { get; set; }
        public Nullable<int> actividad { get; set; }
        public Nullable<int> tiempo { get; set; }
        public Nullable<int> uno { get; set; }
        public Nullable<int> dos { get; set; }
        public Nullable<int> tres { get; set; }
        public Nullable<int> cuatro { get; set; }
        public Nullable<int> cinco { get; set; }
        public Nullable<int> seis { get; set; }
        public Nullable<int> siete { get; set; }
        public Nullable<int> ocho { get; set; }
        public Nullable<int> nueve { get; set; }
        public Nullable<int> diez { get; set; }
        public Nullable<int> once { get; set; }
        public Nullable<int> doce { get; set; }
        public Nullable<int> trece { get; set; }
        public Nullable<int> catorce { get; set; }
        public Nullable<int> quince { get; set; }
        public Nullable<int> diez_y_seis { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> total_cuota { get; set; }
        public Nullable<decimal> total_costo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual actividad actividad1 { get; set; }
        public virtual tiempo tiempo1 { get; set; }
    }
}
