//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    
    public partial class LoginUser_Result2
    {
        public string nom_empleado { get; set; }
        public string apellido { get; set; }
        public Nullable<int> num_departamento { get; set; }
        public string email { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
