//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class partida_nota
    {
        public int id_partida_nota { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> nota_credito { get; set; }
    
        public virtual nota_de_credito nota_de_credito { get; set; }
    }
}
