//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodo_mes
    {
        public int id_periodo_mes { get; set; }
        public string mes { get; set; }
        public Nullable<int> estatus { get; set; }
        public string numero { get; set; }
        public Nullable<int> estatus_tiempo { get; set; }
    }
}
