//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public presupuesto()
        {
            this.presupuesto_gasto = new HashSet<presupuesto_gasto>();
            this.presupuesto_nivel = new HashSet<presupuesto_nivel>();
        }
    
        public int id_presupuesto { get; set; }
        public string nom_presupuesto { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<int> socio { get; set; }
        public Nullable<int> gerente { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<decimal> cotizacion { get; set; }
        public Nullable<decimal> aceptado { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> utilidad { get; set; }
        public Nullable<int> asignado { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> userupd { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual cliente cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presupuesto_gasto> presupuesto_gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presupuesto_nivel> presupuesto_nivel { get; set; }
    }
}
