//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_nivel
    {
        public int id_presupuesto_nivel { get; set; }
        public Nullable<int> presupuesto { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<int> horas { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> personal { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public Nullable<decimal> costo { get; set; }
    
        public virtual nivel nivel1 { get; set; }
        public virtual presupuesto presupuesto1 { get; set; }
    }
}
