//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyecto()
        {
            this.asignacion_de_gastos = new HashSet<asignacion_de_gastos>();
            this.facturas = new HashSet<factura>();
            this.hora_asignable = new HashSet<hora_asignable>();
        }
    
        public int id_proyecto { get; set; }
        public string clave_proyecto { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<int> socio { get; set; }
        public Nullable<int> gerente { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<System.DateTime> fecha_final { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<int> carga_tiempos { get; set; }
        public string fecha_cierre { get; set; }
        public Nullable<int> prorrateable { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> presupuesto { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> userupd { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string clave_proy_old { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion_de_gastos> asignacion_de_gastos { get; set; }
        public virtual cliente cliente1 { get; set; }
        public virtual departamento departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> facturas { get; set; }
        public virtual gerente gerente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hora_asignable> hora_asignable { get; set; }
        public virtual socio socio1 { get; set; }
    }
}
