//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class servidor_correo
    {
        public int id_servidor_correo { get; set; }
        public Nullable<int> puerto { get; set; }
        public string host { get; set; }
        public string ssl { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string displayname { get; set; }
        public string correo { get; set; }
        public string contrasenia { get; set; }
    }
}
