//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposervicio_conceptosat
    {
        public int id_tiposervicio_conceptosat { get; set; }
        public Nullable<int> id_tipo_servicio { get; set; }
        public Nullable<int> id_concepto_sat { get; set; }
    
        public virtual conceptos_sat conceptos_sat { get; set; }
        public virtual tipo_servicio tipo_servicio { get; set; }
    }
}
