//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zona
    {
        public int id_zona { get; set; }
        public string nom_zona { get; set; }
        public string serie { get; set; }
        public Nullable<int> userupd { get; set; }
        public Nullable<System.DateTime> stamp { get; set; }
        public Nullable<int> estatus { get; set; }
    }
}
